# Generated by Django 4.2.25 on 2025-11-15 22:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Grade',
                'verbose_name_plural': 'Assessment Grades',
                'ordering': ['student__last_name', 'student__first_name', '-assessment__course_instance__year', '-assessment__course_instance__semester', 'assessment'],
            },
        ),
    ]
