# Generated by Django 4.2.25 on 2025-12-24 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgrade',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='Score obtained (0-max_score of assessment)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
