# Generated by Django 4.2.25 on 2025-12-20 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GRADE_POSTED', 'Grade Posted'), ('COURSE_ENROLLED', 'Course Enrolled'), ('GENERAL', 'General')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=64, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
