# Generated by Django 4.2.25 on 2025-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the student enrolled (e.g., 2024)', null=True, verbose_name='Enrollment Year'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True, user must change password on next login', verbose_name='Must Change Password'),
        ),
    ]
