# Generated by Django 4.2.25 on 2025-12-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_departmentannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentannouncement',
            name='audience',
            field=models.CharField(choices=[('STUDENTS', 'Students'), ('INSTRUCTORS', 'Instructors'), ('ALL', 'All')], default='ALL', help_text='Target audience for this announcement', max_length=20),
        ),
    ]
