# Generated by Django 4.2.25 on 2025-12-25 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_departmentannouncement_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAnnouncementReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='core.departmentannouncement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Announcement Read Receipt',
                'verbose_name_plural': 'Department Announcement Read Receipts',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
