import { useState, useEffect } from 'react'
import { useAuth } from '../../context/AuthContext'
import { usersAPI } from '../../api/users'
import { departmentsAPI } from '../../api/departments'
import { useToast } from '../../context/ToastContext'
import DataTable from '../../components/DataTable'
import LoadingState from '../../components/LoadingState'
import ErrorState from '../../components/ErrorState'
import FileUploadModal from '../../components/FileUploadModal'
import ConfirmationModal from '../../components/ConfirmationModal'
import DeptStudentsToolbar from '../../components/DeptStudentsToolbar'
import '../../styles/pages.css'

/**
 * Page: Department Student List
 * Displays a list of students in the department with bulk operations
 */
const DeptStudentList = () => {
    const { user } = useAuth()
    const { addToast } = useToast()
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)
    const [students, setStudents] = useState([])

    // Registration State (single student)
    const [showRegister, setShowRegister] = useState(false)
    const [regData, setRegData] = useState({
        first_name: '',
        last_name: '',
        email: '',
        student_id: '',
        role: 'STUDENT'
    })
    const [regLoading, setRegLoading] = useState(false)

    // Bulk Import State
    const [showBulkImport, setShowBulkImport] = useState(false)
    const [bulkImportLoading, setBulkImportLoading] = useState(false)

    // Bulk Delete State
    const [selectedIds, setSelectedIds] = useState(new Set())
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
    const [deleteLoading, setDeleteLoading] = useState(false)

    // Filter State
    const [filters, setFilters] = useState({
        student_id: '',
        name: '',
        email: '',
        enrollment_year: ''
    })

    useEffect(() => {
        loadStudents()
    }, [])

    const loadStudents = async () => {
        try {
            setLoading(true)
            const response = await usersAPI.list({
                role: 'STUDENT',
                department: user.department
            })
            // Handle pagination or direct array
            const data = response.results || response
            setStudents(Array.isArray(data) ? data : [])
            setSelectedIds(new Set()) // Clear selection on reload
        } catch (err) {
            console.error('Failed to load students:', err)
            setError('Failed to load students list')
        } finally {
            setLoading(false)
        }
    }

    // Filter Logic
    const filteredStudents = students.filter(student => {
        const matchId = student.student_id?.toLowerCase().includes(filters.student_id.toLowerCase())
        const fullName = `${student.first_name || ''} ${student.last_name || ''}`.toLowerCase()
        const matchName = fullName.includes(filters.name.toLowerCase())
        const matchEmail = student.email?.toLowerCase().includes(filters.email.toLowerCase())
        const matchYear = student.enrollment_year?.toString().includes(filters.enrollment_year)

        return (filters.student_id === '' || matchId) &&
            (filters.name === '' || matchName) &&
            (filters.email === '' || matchEmail) &&
            (filters.enrollment_year === '' || matchYear)
    })

    // Single student registration (no password - auto generated by backend)
    const handleRegister = async (e) => {
        e.preventDefault()
        if (!regData.first_name || !regData.last_name || !regData.email || !regData.student_id) {
            addToast('All fields are required', 'error')
            return
        }

        try {
            setRegLoading(true)
            await usersAPI.create({
                ...regData,
                username: regData.email,
                department: user.department
            })
            addToast('Student registered successfully. Password is auto-generated.', 'success')
            setShowRegister(false)
            setRegData({ first_name: '', last_name: '', email: '', student_id: '', role: 'STUDENT' })
            await loadStudents()
        } catch (err) {
            console.error('Registration failed:', err)
            const errorData = err.response?.data || {}
            const errorMessage = errorData.detail ||
                Object.entries(errorData)
                    .map(([key, val]) => `${key}: ${Array.isArray(val) ? val.join(' ') : val}`)
                    .join('\n') ||
                'Failed to register student'
            addToast(errorMessage, 'error')
        } finally {
            setRegLoading(false)
        }
    }

    // Bulk import handler
    const handleBulkImport = async (parsedStudents) => {
        if (parsedStudents.length === 0) return

        // Extract department code from the first row
        const fileDeptCode = parsedStudents[0].department_code

        if (!fileDeptCode) {
            addToast('Department code missing in file', 'error')
            return
        }

        // Sanitize students list: delete department_code as it's not in BulkStudentItem schema
        const sanitizedStudents = parsedStudents.map(s => {
            const { department_code, ...rest } = s
            return rest
        })

        try {
            setBulkImportLoading(true)
            const result = await usersAPI.bulkCreateStudents(fileDeptCode, sanitizedStudents)
            addToast(`Successfully created ${result.created_count} students`, 'success')
            setShowBulkImport(false)
            await loadStudents()
        } catch (err) {
            console.error('Bulk import failed:', err)
            const errorData = err.response?.data || {}
            const errorMessage = errorData.detail ||
                errorData.error ||
                JSON.stringify(errorData) ||
                'Bulk import failed'
            addToast(errorMessage, 'error')
        } finally {
            setBulkImportLoading(false)
        }
    }

    // Selection handlers
    const handleSelectAll = () => {
        if (selectedIds.size === filteredStudents.length) {
            setSelectedIds(new Set())
        } else {
            setSelectedIds(new Set(filteredStudents.map(s => s.id)))
        }
    }

    const handleSelectOne = (id) => {
        const newSelected = new Set(selectedIds)
        if (newSelected.has(id)) {
            newSelected.delete(id)
        } else {
            newSelected.add(id)
        }
        setSelectedIds(newSelected)
    }

    // Bulk delete handler
    const handleBulkDelete = async () => {
        if (selectedIds.size === 0) return

        try {
            setDeleteLoading(true)
            // Map selected DB IDs to logical Student IDs (strings)
            const idsToDelete = students
                .filter(s => selectedIds.has(s.id))
                .map(s => s.student_id)

            const result = await usersAPI.bulkDelete(idsToDelete)
            addToast(`Successfully deleted ${result.deleted_count} student(s)`, 'success')
            setShowDeleteConfirm(false)
            await loadStudents()
        } catch (err) {
            console.error('Bulk delete failed:', err)
            addToast('Failed to delete students', 'error')
        } finally {
            setDeleteLoading(false)
        }
    }

    const columns = [
        {
            header: () => (
                <input
                    type="checkbox"
                    checked={filteredStudents.length > 0 && selectedIds.size === filteredStudents.length}
                    onChange={handleSelectAll}
                    title="Select all"
                />
            ),
            accessor: 'select',
            render: (row) => (
                <input
                    type="checkbox"
                    checked={selectedIds.has(row.id)}
                    onChange={() => handleSelectOne(row.id)}
                />
            )
        },
        {
            header: 'Student ID',
            accessor: 'student_id',
            render: (row) => row.student_id || 'N/A'
        },
        {
            header: 'Name',
            accessor: 'first_name',
            render: (row) => `${row.first_name || ''} ${row.last_name || ''}`.trim(),
        },
        { header: 'Email', accessor: 'email' },
        { header: 'Enrollment Year', accessor: 'enrollment_year' },
    ]

    if (loading && students.length === 0 && !showRegister && !showBulkImport) return <LoadingState />
    if (error) return <ErrorState error={error} />

    return (
        <div className="page-container">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
                <h1 className="page-title">Students</h1>
                <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                    {selectedIds.size > 0 && (
                        <button
                            className="btn btn-danger"
                            onClick={() => setShowDeleteConfirm(true)}
                        >
                            Delete Selected ({selectedIds.size})
                        </button>
                    )}
                    <button
                        className="btn btn-secondary"
                        onClick={() => setShowBulkImport(true)}
                    >
                        Bulk Import
                    </button>
                    <button
                        className="btn btn-primary"
                        onClick={() => setShowRegister(true)}
                    >
                        Register Student
                    </button>
                    <button className="btn btn-secondary" onClick={loadStudents}>
                        Refresh
                    </button>
                </div>
            </div>

            {/* Filters */}
            <DeptStudentsToolbar
                filters={filters}
                onFilterChange={(field, value) => setFilters(prev => ({ ...prev, [field]: value }))}
                onReset={() => setFilters({ student_id: '', name: '', email: '', enrollment_year: '' })}
            />

            <div className="info-card" style={{ marginTop: '1rem' }}>
                <p>
                    List of all students in your department. Use <strong>Bulk Import</strong> to add multiple students via Excel or CSV file.
                </p>
                <p style={{ marginTop: '8px', fontSize: '0.9em' }}>
                    Passwords are automatically generated by the system.
                </p>
            </div>

            <DataTable
                columns={columns}
                data={filteredStudents}
                emptyMessage="No students found matching your filters."
            />

            {/* Single Registration Modal - No Password Field */}
            {showRegister && (
                <div className="modal-overlay" onClick={() => setShowRegister(false)}>
                    <div className="modal-content" onClick={e => e.stopPropagation()}>
                        <h3 className="modal-title">Register New Student</h3>
                        <form onSubmit={handleRegister}>
                            <div className="form-group">
                                <label>First Name:</label>
                                <input
                                    type="text"
                                    value={regData.first_name}
                                    onChange={e => setRegData({ ...regData, first_name: e.target.value })}
                                    required
                                />
                            </div>
                            <div className="form-group">
                                <label>Last Name:</label>
                                <input
                                    type="text"
                                    value={regData.last_name}
                                    onChange={e => setRegData({ ...regData, last_name: e.target.value })}
                                    required
                                />
                            </div>
                            <div className="form-group">
                                <label>Email:</label>
                                <input
                                    type="email"
                                    value={regData.email}
                                    onChange={e => setRegData({ ...regData, email: e.target.value })}
                                    required
                                />
                            </div>
                            <div className="form-group">
                                <label>Student ID:</label>
                                <input
                                    type="text"
                                    value={regData.student_id}
                                    onChange={e => setRegData({ ...regData, student_id: e.target.value })}
                                    required
                                />
                            </div>
                            <div style={{
                                background: '#e3f2fd',
                                padding: '12px',
                                borderRadius: '4px',
                                marginBottom: '16px',
                                fontSize: '0.875rem'
                            }}>
                                <strong>Note:</strong> Password will be auto-generated as FirstName+LastName.
                                Student can change it on first login.
                            </div>
                            <div className="modal-actions">
                                <button type="button" className="btn btn-secondary" onClick={() => setShowRegister(false)}>
                                    Cancel
                                </button>
                                <button type="submit" className="btn btn-primary" disabled={regLoading}>
                                    {regLoading ? 'Registering...' : 'Register'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Bulk Import Modal */}
            <FileUploadModal
                isOpen={showBulkImport}
                onClose={() => setShowBulkImport(false)}
                onSubmit={handleBulkImport}
                loading={bulkImportLoading}
                title="Bulk Import Students"
                requiredColumns={['email', 'first_name', 'last_name', 'student_id', 'enrollment_year', 'department_code']}
                optionalColumns={[]}
            />

            {/* Delete Confirmation Modal */}
            <ConfirmationModal
                isOpen={showDeleteConfirm}
                onClose={() => setShowDeleteConfirm(false)}
                onConfirm={handleBulkDelete}
                title="Delete Students"
                message={`Are you sure you want to delete ${selectedIds.size} student(s)? This action cannot be undone.`}
                confirmText={deleteLoading ? 'Deleting...' : 'Delete'}
                confirmVariant="danger"
            />
        </div>
    )
}

export default DeptStudentList
