# Generated by Django 4.2.25 on 2025-11-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programoutcome',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DEPARTMENT_HEAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_program_outcomes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='core.department', verbose_name='Department'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'is_active'], name='core_depart_code_df2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='programoutcome',
            index=models.Index(fields=['department', 'is_active'], name='core_progra_departm_b94004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programoutcome',
            unique_together={('department', 'code')},
        ),
    ]
