# Generated by Django 4.2.25 on 2025-11-04 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Midterm 1, Final Exam, Project 1', max_length=50)),
                ('assessment_type', models.CharField(choices=[('MIDTERM', 'Midterm Exam'), ('FINAL', 'Final Exam'), ('PROJECT', 'Project'), ('HOMEWORK', 'Homework'), ('QUIZ', 'Quiz'), ('LAB', 'Lab')], max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['course', 'assessment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The course code', max_length=10)),
                ('name', models.CharField(help_text='The course name', max_length=100)),
                ('semester', models.CharField(help_text='The semester of the course', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'INSTRUCTOR'), ('role', 'DEPARTMENT_HEAD'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code of the learning outcome', max_length=10)),
                ('description', models.TextField(help_text='The description of the learning outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.course')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['course', 'code'],
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentToLOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_contributions', to='courses.assessment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_contributions', to='courses.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment to Learning Outcome Contribution',
                'verbose_name_plural': 'Assessment to Learning Outcome Contributions',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course'),
        ),
        migrations.CreateModel(
            name='LOtoPOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'DEPARTMENT_HEAD')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lo_po_contributions', to=settings.AUTH_USER_MODEL)),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_contributions', to='courses.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_contributions', to='core.programoutcome')),
            ],
            options={
                'verbose_name': 'Learning Outcome to Program Outcome Contribution',
                'verbose_name_plural': 'Learning Outcome to Program Outcome Contributions',
                'unique_together': {('learning_outcome', 'program_outcome')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'code', 'semester'], name='courses_cou_departm_36ae8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttolocontribution',
            unique_together={('assessment', 'learning_outcome')},
        ),
    ]
