import http from './http'

/**
 * Users API
 * Based on /api/users/ endpoints
 */
export const usersAPI = {
    list: async (params = {}) => {
        const response = await http.get('/users/', { params })
        return response.data
    },

    get: async (id) => {
        const response = await http.get(`/users/${id}/`)
        return response.data
    },

    create: async (data) => {
        const response = await http.post('/users/', data)
        return response.data
    },

    update: async (id, data) => {
        const response = await http.put(`/users/${id}/`, data)
        return response.data
    },

    patch: async (id, data) => {
        const response = await http.patch(`/users/${id}/`, data)
        return response.data
    },

    delete: async (id) => {
        const response = await http.delete(`/users/${id}/`)
        return response.data
    },

    /**
     * Bulk create students - password is auto-generated by backend
     * @param {string} department - Department code (e.g. "CSE")
     * @param {Array} students - Array of student objects
     */
    bulkCreateStudents: async (department, students) => {
        const response = await http.post('/users/bulk_create_students/', {
            department,
            students
        })
        return response.data
    },

    /**
     * Bulk delete multiple students
     * @param {Array} studentIds - Array of student IDs (strings) to delete
     */
    bulkDelete: async (studentIds) => {
        const response = await http.post('/users/bulk_delete_students/', { student_ids: studentIds })
        return response.data
    },

    /**
     * Get student dashboard data (single API call for all dashboard info)
     * Students only - returns own data
     */
    getMyDashboard: async () => {
        const response = await http.get('/users/my/dashboard/')
        return response.data
    },

    /**
     * Get detailed PO achievements for a student
     * @param {string|number} studentId - Database ID or student number
     */
    getStudentPOAchievements: async (studentId) => {
        const response = await http.get(`/achievements/student/${studentId}/`)
        return response.data
    },

    /**
     * Get GPA information for a user
     * @param {number} userId - User ID
     */
    getGPA: async (userId) => {
        const response = await http.get(`/users/${userId}/gpa/`)
        return response.data
    },
}
