# Generated by Django 4.2.25 on 2025-11-15 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Midterm 1, Final Exam, Project 1', max_length=50)),
                ('assessment_type', models.CharField(choices=[('MIDTERM', 'Midterm Exam'), ('FINAL', 'Final Exam'), ('PROJECT', 'Project'), ('HOMEWORK', 'Homework'), ('QUIZ', 'Quiz'), ('LAB', 'Lab')], max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of this assessment towards the final course grade ex: 20 for 20%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Contribution weight to final grade (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['course_instance', 'assessment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentToLOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment to Learning Outcome Contribution',
                'verbose_name_plural': 'Assessment to Learning Outcome Contributions',
            },
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Ex: Fall 2024', max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Ex: 2024')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['department', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code of the learning outcome', max_length=10)),
                ('description', models.TextField(help_text='The description of the learning outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['course_template', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LOtoPOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Outcome to Program Outcome Contribution',
                'verbose_name_plural': 'Learning Outcome to Program Outcome Contributions',
            },
        ),
    ]
