# Generated by Django 4.2.25 on 2025-11-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotopocontribution',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'DEPARTMENT_HEAD')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lo_po_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotopocontribution',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_contributions', to='courses.learningoutcome'),
        ),
        migrations.AddField(
            model_name='lotopocontribution',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_contributions', to='core.programoutcome'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='course_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.coursetemplate'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_templates', to='core.department'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='course_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='courses.coursetemplate'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'INSTRUCTOR'), ('role', 'DEPARTMENT_HEAD'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='students',
            field=models.ManyToManyField(limit_choices_to=models.Q(('role', 'STUDENT')), related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttolocontribution',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_contributions', to='courses.assessment'),
        ),
        migrations.AddField(
            model_name='assessmenttolocontribution',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_contributions', to='courses.learningoutcome'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.courseinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='lotopocontribution',
            unique_together={('learning_outcome', 'program_outcome')},
        ),
        migrations.AlterUniqueTogether(
            name='learningoutcome',
            unique_together={('course_template', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='coursetemplate',
            unique_together={('department', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='courseinstance',
            unique_together={('course_template', 'semester', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttolocontribution',
            unique_together={('assessment', 'learning_outcome')},
        ),
    ]
