# Generated by Django 4.2.25 on 2025-12-22 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_assessmenttolocontribution_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='target_class_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Target class year for this course (1-6). Helps filter students during enrollment.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Target Class Year'),
        ),
    ]
