# Generated by Django 4.2.25 on 2025-12-24 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_update_lo_po_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotopocontribution',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Department head who approved or declined this contribution', limit_choices_to=models.Q(('role', 'DEPARTMENT_HEAD')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lo_po_contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
