# Generated by Django 4.2.25 on 2025-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courseannouncementreadreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the assessment', null=True),
        ),
    ]
