# Generated by Django 4.2.25 on 2025-12-28 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_add_assessment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the course was finalized and grades locked', null=True),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='User who finalized this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
