# Generated by Django 4.2.25 on 2025-11-04 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.assessment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_assessment_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Grade',
                'verbose_name_plural': 'Assessment Grades',
                'ordering': ['student', 'assessment__course'],
                'indexes': [models.Index(fields=['student', 'assessment'], name='grades_asse_student_6848cf_idx'), models.Index(fields=['assessment', 'score'], name='grades_asse_assessm_bd6782_idx')],
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
