# Generated by Django 4.2.25 on 2025-11-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentgrade',
            name='entered_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'INSTRUCTOR'), ('role', 'DEPARTMENT_HEAD'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_assessment_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentgrade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assessmentgrade',
            index=models.Index(fields=['student', 'assessment'], name='grades_asse_student_6848cf_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrade',
            index=models.Index(fields=['assessment', 'score'], name='grades_asse_assessm_bd6782_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentgrade',
            index=models.Index(fields=['assessment', 'student'], name='grades_asse_assessm_e50fa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentgrade',
            unique_together={('student', 'assessment')},
        ),
    ]
